---
title: "Heian Godan"
lang: fr
---

Dernier kata de la série initiatique *Heian*, son appellation peut se traduire par « paix et tranquillité, niveau cinq ».

:::: {.grid}

::: {.g-col-8}
Vidéo du kata à venir.
<!--
{{< video videos/katas/heian_godan.mp4
    aria-label="Démonstration du kata Heian Godan"
    title="Kata Heian Godan"
>}}
-->

:::

::: {.g-col-4}

```{=html}
<figure>
  <svg viewBox="0 0 500 420" xmlns="http://www.w3.org/2000/svg">
    <title>Embusen de Heian Godan</title>

    <g stroke="black" stroke-width="2.5" stroke-linecap="round" fill="none">
      <line x1="220" y1="340" x2="140" y2="340"/>
      <line x1="220" y1="340" x2="220" y2="100"/>
    </g>

    <circle cx="220" cy="340" r="12" fill="#C0202A"/>
  </svg>
  <figcaption class="text-center">Embusen de Heian Godan</figcaption>
</figure>
```

:::

::::

## Séquence 1

**Techniques :**

- Vers la gauche, *uchi-uke* en *kōkutsu-dachi* gauche.
- Sur place, *chūdan gyaku-zuki* en *kōkutsu-dachi* gauche.
- Sur place, *chūdan kagi-zuki* en *heisoku-dachi*.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

1. Tori attaque *gyaku-zuki* au corps. Uke bloque *uchi-uke* et contre *gyaku-zuki*.
2. Uke remonte en *heisoku-dachi* et frappe *kagi-zuki*.

### Avancé

Tori est en garde droite, uke en garde gauche.

1. Tori attaque *oi-zuki* au corps. Uke bloque *gyaku-uchi-uke* et agrippe le poignet de tori. Dans le même temps, il passe le bras avant sous celui de tori afin d’appliquer un *ude-gatame* dans une forme de *uchi-uke*.  
**Remarque :** pour bien effectuer la clé de coude, il est important que uke s’efface en pivotant vers l’intérieur afin de laisser tori ouvrir son épaule.
2. Uke repousse le bras de tori et rentre *gyaku-zuki* en *kōkutsu-dachi* avec un sursaut avant.
3. Dans le dernier temps, uke remonte pour frapper tori avec un coup de coude du bras avant.

### Enchaîné avec la séquence 2

Tori et uke sont en garde gauche.

1. Tori attaque *oi-zuki* au corps. Uke se décale en *mawari-ashi* pour bloquer *uchi-uke* et contrer dans le même temps *gyaku-zuki*.
2. Uke saisit le poignet de tori des deux mains et passe sous son bras pour amorcer un *waki-gatame* sans amener tori au sol.
3. Reprise de distance en garde gauche. Tori attaque à nouveau *oi-zuki* au corps. Uke pivote à angle droit vers la gauche pour bloquer *uchi-uke* en *kōkutsu-dachi* droite, sur l’extérieur de tori.
4. Uke saisit le poignet de tori puis contre *gyaku-zuki*.
5. Uke remonte sur sa posture et exécute un *empi* descendant dans le creux du coude de tori.
6. Uke enroule sa main par le dessus et vers l’intérieur pour agripper son propre poignet dans une prise en triangle.
7. Uke pivote de l’autre côté pour faire chuter tori en accompagnant avec un *ko-soto-gari*.

:::

## Séquence 2

**Techniques :**

- Vers la droite, *uchi-uke* en *kōkutsu-dachi* droite.
- Sur place, *chūdan-gyaku-zuki* en *kōkutsu-dachi* droite.
- Sur place, *chūdan-kagi-zuki* en *heisoku-dachi*.

::: {.panel-tabset}

### Bunkai de base

Tori est en garde gauche, uke en garde droite.

1. Tori attaque *oi-zuki* au corps. Uke bloque *uchi-uke* en effectuant un déplacement *mawari-ashi* puis rentre *gyaku-zuki* en *kōkutsu-dachi* avec un sursaut.
2. Uke remonte sur sa posture afin de terminer par un étranglement arrière *hadaka-jime*.

### Avancé

Tori effectue une saisie directe main droite au col.

1. Uke saisit main arrière le même pan de son kimono où tori a effectué la saisie. De l’autre main, il passe sous le bras de tori pour prendre le *kumikata* en garde opposée. Il recule ensuite la jambe gauche pour tendre le bras de tori et lui faire lâcher sa prise.
2. Uke rentre de suite *gyaku-zuki* avec un léger sursaut avant.
3. Uke termine avec *waki-gatame*.

:::

## Séquence 3

**Techniques :**

- Vers l’avant, *morote-uke* en *kōkutsu-dachi* droite.
- En avançant, *gedan-jūji-uke* en *zenkutsu-dachi* gauche.
- Sur place, *jōdan-shutō-jūji-uke* en *zenkutsu-dachi* gauche.
- Sur place, *osae-uke* en *zenkutsu-dachi* gauche.
- Sur place, *tettsui-uchi* en *zenkutsu-dachi* gauche.
- En avançant, *chūdan-oi-zuki* en *zenkutsu-dachi* droite avec le **kiai**.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde droite.

1. Tori attaque *oi-zuki* au corps. Uke bloque *morote-uke*.
2. Tori enchaîne *mae-geri* au corps suivi de *kizami-zuki* à la tête. Uke recule pour bloquer *jūji-uke* suivi de *shutō-jūji-uke*.
3. Uke effectue un *waki-gatame* avant de contrer *tettsui-uchi* sur place.
4. Uke change de garde et fait chuter tori grâce à un *ō-soto-gari*.

### Avancé

Tori et uke sont en garde droite.

1. Tori attaque *oi-zuki* au corps. Uke bloque *uchi-uke* et contre dans le même *gyaku ura-zuki* en effectuant un pivot en *mawari-ashi*.
2. Reprise de distance, tori en garde gauche. Tori attaque *mae-geri* jambe arrière. Uke bloque *gedan-barai* en reculant puis contre *gyaku-zuki*.
3. Reprise de distance, tori en garde droite. Tori attaque *oi-zuki* à la tête. Uke bloque *shutō-age-uke* du bras avant et remise *shutō-uchi* à la gorge du bras arrière.
4. Uke termine avec *tai-otoshi*, le bras qui tire figurant le *tettsui* et la frappe au sol pour le dernier *zuki*.

:::

## Séquence 4

**Techniques :**

- Demi-tour en rotation autour du pied arrière, *gedan-barai* en *kiba-dachi* droite.
- Demi-tour sur place, *haishu-uke* en *kiba-dachi* gauche.
- En avançant, *mikatsuki-geri* jambe arrière puis, en retombant, *empi-uchi* en *kiba-dachi* droite.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde droite.

1. Tori attaque *mae-geri* au corps. Uke bloque *gedan-barai*.
2. Tori enchaîne *oi-zuki* au corps. Uke bloque *haishu-uke* en reculant en *kiba-dachi*.
3. Uke saisit le poignet de tori et remise *mikazuki-geri* et, en retombant, administre un coup de coude dans les côtes.

:::

## Séquence 5

**Techniques :**

- Sur place, *morote-uke* en *kōsa-dachi* droite.
- Demi-tour sur place, *morote-kōhō-zuki-age* en *renoji-dachi*.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde droite.

1. Tori attaque *oi-zuki* au corps. Uke bloque *uchi-uke* puis remise *gyaku-zuki* en *kōsa-dachi*.
2. Uke lâche la nuque de tori mais saisit son bras de la main gauche. Il recule ensuite la jambe arrière pour frapper du bras droit avec un coup de coude remontant.

:::

## Séquence 6

**Techniques :**

- En sautant vers l’avant avec quart de tour vers la gauche, *gedan-jūji-uke* en *kōsa-dachi* droite.
- Pivot vers l’avant *morote-uke* en *zenkutsu-dachi* droite.

::: {.panel-tabset}

### Bunkai de base



:::

## Séquence 7

**Techniques :**

- Demi-tour sur place, *nagashi-uke* bras avant et *shutō-uchi* bras arrière en *zenkutsu-dachi* gauche.
- Sur place, *manji-kamae* en *kōkutsu-dachi* gauche.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

1. Tori attaque *oi-zuki* à la tête. Uke bloque *nagashi-uke* et remise *shutō-uchi* au niveau de la cuisse.
2. Uke saisit le pantalon de tori de la main droite et son col de la main gauche puis le fait chuter par-dessus sa jambe avancée.

:::

## Séquence 8

**Techniques :**

- Demi-tour sur place en ramenant la jambe avant, *manji-kamae* en *heisoku-dachi*.
- Sur place, *nagashi-uke* bras avant et *shutō-uchi* bras arrière en *zenkutsu-dachi* droite.
- Sur place, *manji-kamae* en *kōkutsu-dachi* droite.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde droite.

1. Tori attaque *oi-zuki* au corps. Uke dévie l’attaque une première fois avec *soto-uke* puis l’écarte complètement avec un *gyaku-uchi-uke* quand l’autre bras remise dans le même temps *tettsui-uchi* dans les côtes.
2. Reprise de distance, tori en garde gauche. 

:::
