---
title: "Heian Yondan"
lang: fr
---

Quatrième kata de la série initiatique *Heian*, son appellation peut se traduire par « paix et tranquillité, niveau quatre ».

:::: {.grid}

::: {.g-col-8}
Vidéo du kata à venir.
<!--
{{< video videos/katas/heian_yondan.mp4
    aria-label="Démonstration du kata Heian Yondan"
    title="Kata Heian Yondan"
>}}
-->

:::

::: {.g-col-4}

```{=html}
<figure>
  <svg viewBox="0 0 500 420" xmlns="http://www.w3.org/2000/svg">
    <title>Embusen de Heian Yondan</title>

    <g stroke="black" stroke-width="2.5" stroke-linecap="round" fill="none">
      <line x1="220" y1="340" x2="140" y2="340"/>
      <line x1="220" y1="340" x2="220" y2="180"/>
      <line x1="220" y1="180" x2="140" y2="180"/>
      <line x1="220" y1="180" x2="220" y2="20"/>
      <line x1="220" y1="20"  x2="334" y2="134"/>
      <line x1="277" y1="77"  x2="163" y2="163"/>
      <line x1="220" y1="340" x2="220" y2="420"/>
    </g>

    <circle cx="220" cy="340" r="12" fill="#C0202A"/>
  </svg>
  <figcaption class="text-center">Embusen de Heian Yondan</figcaption>
</figure>
```

:::

::::

## Séquence 1

**Techniques :**

- Vers la gauche, *haishu-uke* des deux bras en *kōkutsu-dachi* gauche.
- Demi-tour vers la droite, *haishu-uke* des deux bras en *kōkutsu-dachi* droite.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

1. Tori attaque *mawashi-geri* à la tête. Uke bloque *tate-haishu-uke* du bras avant.
2. Tori enchaîne *gyaku-zuki* à la tête. Uke bloque *shutō-age-uke* du bras arrière.
3. Tori termine avec un *zuki* au corps sur place. Uke bloque *osae-uke* du bras avant tout en changeant de garde.
4. Uke remise *shutō-uke* sans attendre la fin du déplacement.

:::

## Séquence 2

**Techniques :**

- Pivot à angle droit, *gedan jūji-uke* en *zenkutsu-dachi* gauche.
- En avançant, *morote-uke* en *kōkutsu-dachi* droite.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

1. Tori attaque *mae-geri* jambe arrière. Uke bloque *jūji-uke*.
2. Tori enchaîne *oi-zuki* au corps. Uke recule pour bloquer *uchi-uke* en *kōkutsu-dachi* droite avant de remiser avec un uppercut arrière.

:::

## Séquence 3

**Techniques :**

- Sur place, *yoko-geri-kekomi* à angle droit vers la gauche accompagné d’un *uraken-uchi*.
- En reposant, *gyaku empi-uchi* en *zenkutsu-dachi* gauche.
- Demi-tour, *yoko-geri-kekomi* vers la droite accompagné d’un *uraken-uchi*.
- En reposant, *gyaku empi-uchi* en *zenkutsu-dachi* droite.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

1. Tori attaque *oi-zuki* à la tête. Uke bloque *uraken-uchi*.
2. Uke saisit le poignet de tori avant de remiser *yoko-geri* jambe avant suivi d’un coup de coude en retombant.
3. Uke passe en dessous du bras de tori puis change sa saisie avant d’effectuer un *fumi-komi* sur la jambe avancée de tori pour le forcer à mettre un genou en terre.
4. Uke termine par un coup de coude sur la nuque de tori.
5. **Optionnel :** uke peut finir avec un étranglement *hadaka-jime*.

:::

## Séquence 4

**Techniques :**

- Sur place, *gedan shuto-barai* bras gauche et *shutō-age-uke* du bras droit.
- Pivot vers l’avant, *shuto-uchi* bras droit et *shutō-age-uke* bras gauche en *zenkutsu-dachi* gauche.
- En avançant, *mae-geri* jambe arrière suivi de *uraken-tate-uchi* en reposant en *kosa-dachi* droite avec le **kiai**.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

1. Tori attaque *mae-geri* au corps de la jambe arrière suivi de *gyaku-zuki* à la tête. Uke recule et bloque le coup de pied avec un *shutō-barai* du bras arrière et, pour l’attaque à la tête, *shutō-age-uke*.
2. Tori enchaîne *maete-zuki* à la tête. Dans le même temps, uke bloque *shutō-age-uke* bras arrière et contre *shutō-uchi* à la gorge avec le bras avant.
3. Uke frappe *mae-geri* jambe arrière, obligeant tori à reculer
4. Uke termine avec *uraken*.

### Avancé

Tori et uke sont en garde droite.

1. Tori attaque *mae geri* jambe arrière. Uke pivote vers la droite *ushiro-mawari-ashi* et bloque *sukui-uke* du bras arrière pour rediriger l’attaque de tori bien vers la gauche.
2. Emporté par le mouvement de défense, tori effectue une rotation complète pour attaquer *uraken*. Uke bloque *shutō-age-uke* puis enroule son bras autour de celui de tori, en passant par-dessus, et vient ensuite lui agripper le col.
3. De l’autre bras, uke frappe coup de coude dans la nuque de tori.
4. Uke enchaîne avec un *mae-geri* dans le creux poplité de tori pour lui faire perdre un appui et en profite pour le tirer vers le sol.
5. Dans la chute, uke dégage son bras et frappe *uraken* pour terminer.

:::

## Séquence 5

**Techniques :**

- Grande rotation vers la droite dans la diagonale, *kakiwake-uke* en *kōkutsu-dachi* gauche.
- En avançant, *mae-geri* jambe arrière en *zenkutsu-dachi* droite.
- Sur place, *chūdan oi-zuki* suivi de *gyaku-zuki*.

::: {.panel-tabset}

### Bunkai de base

Tori saisit le col de uke des deux mains.

1. Uke effectue une double frappe *ura-zuki* au menton puis dégage *kakiwake*.
2. Uke attrape la nuque de tori et enchaîne avec un coup de genou.
3. Uke repousse tori avec le bras avant et termine avec *gyaku-zuki*.

:::

## Séquence 6

**Techniques :**

- Pivot à angle droit, *kakiwake-uke* en *kōkutsu-dachi* droite.
- En avançant, *mae-geri* jambe arrière en *zenkutsu-dachi* gauche.
- Sur place, *chūdan oi-zuki* suivi de *gyaku-zuki*.

::: {.panel-tabset}

### Bunkai de base

:::

## Séquence 7

**Techniques :**

- Pivot vers l’axe principal, *morote-uke* en *kōkutsu-dachi* gauche.
- En avançant, *morote-uke* en *kōkutsu-dachi* droite.
- En avançant, *morote-uke* en *kōkutsu-dachi* gauche.

::: {.panel-tabset}

### Bunkai de base

:::

## Séquence 8

**Techniques :**

- Sur place, basculer en *zenkutsu-dachi* gauche et tendre les bras avec les mains au niveau de la tête.
- En avançant, *hiza-geri* avec le **kiai**.
- Demi-tour, *shuto-uke* en *kōkutsu-dachi* gauche.
- En avançant, *shuto-uke* en *kōkutsu-dachi* droite.

::: {.panel-tabset}

### Bunkai de base

:::
