---
title: "Tekki Shodan"
lang: fr
---

Premier kata de la série avancée *Tekki*, son appellation peut se traduire par « cavalier de fer, niveau un ».

:::: {.grid}

::: {.g-col-8}
Vidéo du kata à venir.
<!--
{{< video videos/katas/tekki_shodan.mp4
    aria-label="Démonstration du kata Tekki Shodan"
    title="Kata Tekki Shodan"
>}}
-->

:::

::: {.g-col-4}

```{=html}
<figure>
  <svg viewBox="0 0 500 420" xmlns="http://www.w3.org/2000/svg">
    <title>Embusen de Tekki Shodan</title>

    <g stroke="black" stroke-width="2.5" stroke-linecap="round" fill="none">
      <line x1="220" y1="340" x2="140" y2="340"/>
      <line x1="220" y1="340" x2="300" y2="340"/>
    </g>

    <circle cx="220" cy="340" r="12" fill="#C0202A"/>
  </svg>
  <figcaption class="text-center">Embusen de Tekki Shodan</figcaption>
</figure>
```

:::

::::

## Séquence 1

**Techniques :**

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde droite.

1. Tori attaque oi-zuki chūdan. Uke bloque haishu-uke avant d’agripper le poignet par l’extérieur.
2. Uke remise yoko-geri-kekomi chūdan et, en retombant en kiba-dachi, frappe kagi-zuki.

:::

## Séquence 2

**Techniques :**

::: {.panel-tabset}

### Bunkai de base

Tori est en garde droite, uke en garde gauche.

1. Tori attaque gyaku-zuki chūdan en tsugi-ashi. Uke bloque gyaku uchi-uke.
2. Tori enchaîne mae-geri chūdan jambe arrière posée devant suivi de gyaku-zuki jōdan. Uke bloque le coup de pied avec un gyaku gedan-barai et le coup de poing avec un jōdan age-uke avant de terminer la séquence par un uraken-uchi.
3. **Optionnel :** Uke attrape la nuque de uke après le uraken-uchi et, avec le bras arrière frappe empi-uchi.

:::

## Séquence 3

**Techniques :**

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

1. Tori attaque mawashi-geri gedan suivi de kizami-zuki. Uke absorbe le coup de pied avec nami-gaeshi et bloque le zuki avec kake-uke.
2. Tori enchaîne avec un gyaku-zuki chūdan que uke bloque bras avant en soto-uke. Uke remise gyaku ura-zuki tout en passant le bras avant à l’extérieur du bras avant de tori. Uke termine la séquence par un ude-gatame.

:::
