---
title: "Bunkai : Heian Godan"
lang: fr
---

## Séquence 1

Tori est en garde droite, uke en garde gauche

1. Tori attaque oi-zuki chūdan. Uke amorce un blocage gyaku nagashi-uke avant d’agripper le poignet de tori par l’intérieur et, dans le même temps, le bras avant effectue un uchi-uke afin d’effectuer une clé de coude.
2. Uke repousse du bras avant celui de tori qui était cisaillé et rentre gyaku-zuki en kōkutsu-dachi avec un yori-ashi.
3. Dans le dernier temps, uke remonte en heisoku-dachi tout en attrapant la nuque de tori avec le bras arrière et empi bras avant.

## Séquence 2

Tori est en garde gauche, uke en garde droite.

1. Tori attaque oi-zuki chūdan. Uke effectue un déplacement mawari-ashi à angle droit de l’attaque tout en bloquant uchi-uke, puis rentre gyaku-zuki en kōkutsu-dachi avec un yori-ashi.
2. Uke poursuit en remontant sur sa posture afin de se rapprocher de tori et de terminer en hadaka-jime ou tate-ushiro-jime.

## Séquence 3

Tori et uke sont en garde droite.

1. Tori attaque oi-zuki chūdan. Uke se décale en mawari-ashi tout en éxécutant dans le même temps un blocage uchi-uke et un gyaku ura-zuki.
2. Reprise de distance. Tori, maintenant en garde gauche, attaque mae-geri chūdan. Uke bloque gedan-barai avec un changement de garde et remise gyaku-zuki chūdan.
3. Reprise de distance. Tori est garde droite, uke garde gauche. Tori attaque oi-zuki jōdan. Uke bloque gyaku age-shuto-uko et contre shuto-uchi à la gorge.

## Séquence 4

Tori et uke sont en garde gauche.

1. Tori attaque oi-zuki jōdan. Uke bloque jūji-uke jōdan.
2. Tori enchaîne gyaku-zuki chūdan. Uke bloque osae-uke en tirant son hikite puis remise tettsui-uchi bras avant.
3. Uke poursuit mae-geri chūdan pour faire reculer tori et termine oi-zuki.

## Séquence 5

Tori et uke sont en garde gauche.

1. Tori attaque oi-zuki chūdan. Uke bloque haishu-uke en kiba-dachi puis remise mikazuki-geri tout en saisissant le poignet de tori avant de retomber empi-uchi dans ses côtes.
2. Uke remonte en renoji-dachi avec un second empi-uchi, cette fois-ci au niveau jōdan. Il attrape la nuque de tori et, dans un mouvement de hanche, appuie dessus tout en frappant ura-zuki.

## Séquence 6

Tori est en garde droite, uke en garde gauche.

1. Tori attaque oi-zuki chūdan. Uke bloque haishu-uke en kiba-dachi puis remise mikazuki-geri tout en saisissant le poignet de tori avant de retomber empi-uchi dans ses côtes.
2. Uke, collé à tori, passe son bras droit au-dessus de son épaule pour aller coiffer sa main, le pouce sur le dos. Uke exerce une pression de la poitrine sur le coude de tori pour le faire tourner tori avant de finaliser en kote-gaeshi dans un mouvement de rotation et l’emmener au sol en chute arrière.
3. Pour bien terminer la clé, passer le tibia droit sous l’épaule puis exercer une pression continue vers l’extérieur sur le poignet.

## Séquence 7

Tori est en garde gauche, uke en garde droite.

1. Tori attaque oi-zuki jōdan. Uke bloque soto-uke puis, en saisissant le bras de tori avec la main arrière, remise uraken-uchi en renoji-dachi.
2. La paume de la main droite de uke se place sous le menton de tori pendant que sa jambe avant passe par-dessus de la sienne afin d’effectuer un ō-soto-gari qui amène tori au sol.
3. Uke termine la séquence en croisant sa jambe par-dessus le bras saisi de tori. Le bras droit de uke appuie sur le creux du coude de tori pendans que l’autre main fait pression pour fléchir le bras de tori. Uke saisit maintenant de la main droite le poignet de sa propre main gauche et, en plaquant l’avant-bras de tori contre son torse, il exerce une pression continue en tirant son hikite gauche.

## Séquence 8

Tori et uke sont en garde gauche.

1. Tori attaque oi-zuki jōdan. Uke bloque nagashi-uke et remise gyaku shuto-uchi niveau gedan pour saisir l’intérieur de la cuisse de tori tandis que l’autre main vient s’enclencher loin sous sa gorge afin de saisir le kimono. La main gauche tire (hikite) tandis que la droite soulève (tsurite).
