---
title: "Bunkai : Tekki Shodan"
lang: fr
---

## Séquence 1

Tori et uke sont en garde droite.

1. Tori attaque oi-zuki chūdan. Uke bloque haishu-uke avant d’agripper le poignet par l’extérieur.
2. Uke remise yoko-geri-kekomi chūdan et, en retombant en kiba-dachi, frappe kagi-zuki.

## Séquence 2

Tori est en garde droite, uke en garde gauche.

1. Tori attaque gyaku-zuki chūdan en tsugi-ashi. Uke bloque gyaku uchi-uke.
2. Tori enchaîne mae-geri chūdan jambe arrière posée devant suivi de gyaku-zuki jōdan. Uke bloque le coup de pied avec un gyaku gedan-barai et le coup de poing avec un jōdan age-uke avant de terminer la séquence par un uraken-uchi.
3. **Optionnel :** Uke attrape la nuque de uke après le uraken-uchi et, avec le bras arrière frappe empi-uchi.

## Séquence 3

Tori et uke sont en garde gauche.

1. Tori attaque mawashi-geri gedan suivi de kizami-zuki. Uke absorbe le coup de pied avec nami-gaeshi et bloque le zuki avec kake-uke.
2. Tori enchaîne avec un gyaku-zuki chūdan que uke bloque bras avant en soto-uke. Uke remise gyaku ura-zuki tout en passant le bras avant à l’extérieur du bras avant de tori. Uke termine la séquence par un ude-gatame.
