## Séquence 8

**Techniques :**

- Sur place, basculer en *zenkutsu-dachi* gauche et tendre les bras avec les mains au niveau de la tête.
- En avançant, *hiza-geri* avec le **kiai**.
- Demi-tour, *shuto-uke* en *kōkutsu-dachi* gauche.
- En avançant, *shuto-uke* en *kōkutsu-dachi* droite.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

1. Tori attaque *oi-zuki* au corps. Uke bloque *morote-uke* en pivotant *mawari-ashi*.
2. Uke attrape la tête de tori et frappe coup de genou.
3. Uke effectue un demi-tour et, en retombant en *kōkutsu-dachi*, frappe coup de coude arrière.

### Intermédiaire

Tori et uke sont en garde gauche.

1. Tori attaque *oi-zuki* au corps. Uke bloque *uchi-uke* en pivotant *mawari-ashi* et, dans le même temps, contre *ura-zuki* en *kōkutsu-dachi*.
2. Uke attrape la tête de tori et frappe coup de genou.
3. Uke effectue un demi-tour et, en retombant en *kōkutsu-dachi*, frappe coup de coude arrière.
4. Uke termine avec *ō-goshi*.

### Avancé

Tori et uke sont en garde gauche.

1. Tori attaque *oi-zuki* au corps. Uke bloque *soto-uke* et enchaîne *uraken* à la tête puis *ura-zuki* au corps.
2. Reprise de distance, tori en garde droite. Tori tente à son tour une attaque *uraken* au visage. Uke bloque *gyaku-haitō-uchi-uke* puis saisit le poignet de tori avant de frapper *soto-uke* au niveau du coude.
3. Uke enchaîne avec un *mae-geri* au corps suivi d’un *ō-soto-gari* pour faire chuter tori.

:::
