## Séquence 5

**Techniques :**

- Grande rotation autour du pied arrière, puis *shutō-uke* en *kōkutsu-dachi* gauche.
- En avançant dans la diagonale intérieure, *shutō-uke* en *kōkutsu-dachi* droite.

::: {.panel-tabset}

### Bunkai de base

Tori et uke sont en garde gauche.

Tori attaque *oi-zuki* au corps. Uke bloque *shuto-uke* en *kōkutsu-dachi* grâce à un déplacement *mawari-ashi* avant d’effectuer un changement de garde et de contrer *shutō-uke* à la gorge.

### Enchaîné avec la séquence 6

Tori et uke sont en garde gauche.

1. Tori attaque *oi-zuki* au corps. Uke bloque *shuto-uke* en *kōkutsu-dachi* en se décalant vers l’intérieur. Il saisit le poignet de tori, effectue un changement de jambes et contre *shuto-uke* à la gorge en avançant en *kōkutsu-dachi*. Tori se remet en garde en reculant.
2. Tori est garde gauche et uke garde droite. Tori attaque à nouveau *oi-zuki* au corps. Uke bloque toujours *shuto-uke* en *kōkutsu-dachi* mais en se décalant cette fois-ci vers l’extérieur. Il saisit ensuite le poignet de tori et contre en frappant *soto-uke* au niveau du coude du bras tendu et amène tori au sol avec *ude-hishigi-waki-gatame*.

:::
